### ISSUE TITLE
how can use vs2022 remote debug .net cf 3.5?

### ISSUE THREAD

**Issue by zhouji0212** [scottpidzarko/CrestronSandboxBuildSample#1]

**Comment by scottpidzarko** [comment]
This repository is focused on providing build processes for developing Crestron programs and libraries that conform to the sandbox for 3 series processors.

This is not a fork or recreation of the Crestron plugin for Visual Studio 2008, which provides the ability to do remote debugging. I do not have plans at this time to provide that functionality as I'm not sure if it's possible, and more importantly I don't have the time to pursue that after hours, for free.
